'******************************************************************************************
'Copyright(C) 2020 Xarial Pty Limited
'Reference: https://www.codestack.net/solidworks-api/import-export/export-sheets-pdf/
'License: https://www.codestack.net/license/
'******************************************************************************************
' Moddified by Snake 60::(28.11.2020):: version 1.0.0
'  - macros save drawing in PDF-format in precreated PDF folder and open it
'******************************************************************************************

Const INCLUDE_DRAWING_NAME As Boolean = True

Dim swApp As SldWorks.SldWorks
Dim swModel As SldWorks.ModelDoc2

Dim outFile As String
Dim outFolder As String


Sub main()

    Set swApp = Application.SldWorks
    
try_:
    
    On Error GoTo catch_
    
    Dim swDraw As SldWorks.DrawingDoc
    
    Set swDraw = swApp.ActiveDoc
    
    
    Set swModel = swDraw
        
    If swModel.GetPathName() = "" Then
        Err.Raise vbError, "", "Пожалуйста, сохраните чертеж!"
    End If
        
    Dim vSheetNames As Variant
    vSheetNames = swDraw.GetSheetNames
    
    Dim i As Integer
    
    For i = 0 To UBound(vSheetNames)
        
        Dim sheetName As String
        sheetName = vSheetNames(i)
        
        Dim swExpPdfData As SldWorks.ExportPdfData
        Set swExpPdfData = swApp.GetExportFileData(swExportDataFileType_e.swExportPdfData)
        
        Dim errs As Long
        Dim warns As Long
        
        Dim expSheets(0) As String
        expSheets(0) = sheetName
        
        swExpPdfData.ExportAs3D = False
        swExpPdfData.ViewPdfAfterSaving = False
        swExpPdfData.SetSheets swExportDataSheetsToExport_e.swExportData_ExportSpecifiedSheets, expSheets
        
        Dim drawName As String
        drawName = swModel.GetPathName()
        drawName = Mid(drawName, InStrRev(drawName, "\") + 1, Len(drawName) - InStrRev(drawName, "\") - Len(".slddrw"))
        

        outFile = swModel.GetPathName()
        outFile = Left(outFile, InStrRev(outFile, "\"))
        'outFile = outFile & IIf(INCLUDE_DRAWING_NAME, drawName & "_", "") & sheetName & ".pdf"
        outFolder = outFile & "PDF" & "\"
        outFile = outFolder & IIf(INCLUDE_DRAWING_NAME, drawName, "") & ".pdf"

        
        If False = swModel.Extension.SaveAs(outFile, swSaveAsVersion_e.swSaveAsCurrentVersion, swSaveAsOptions_e.swSaveAsOptions_Silent, swExpPdfData, errs, warns) Then

            Err.Raise vbError, "", "Не удалось сохранить PDF в " & outFile
        End If
        
    Next
    
    OpenFolder
    
    GoTo finally_
    
catch_:
    
    swApp.SendMsgToUser2 Err.Description, swMessageBoxIcon_e.swMbStop, swMessageBoxBtn_e.swMbOk
    
finally_:
    
End Sub

Sub OpenFolder()
Set swApp = Application.SldWorks
Set swModel = swApp.ActiveDoc
OpenExplorerWithFileSelected (outFile)
End Sub

Sub OpenExplorerWithFileSelected(filepath$)
'Test for file exists
retval = Dir(filepath$)
If retval <> "" Then
    'If Exists, then open Windows Explorer and select
    shellparm = "/select," & filepath$
    Shell "explorer """"" & shellparm & """""", vbNormalFocus
End If
End Sub